repos:
- id: "/.*/"
  workflow: terragrunt

workflows: 
  terragrunt:
    plan:
      steps:
      - env:
          name: TF_WORKSPACE
          command: echo $WORKSPACE
      - run: terragrunt plan -input=false

    apply:
      steps:
      - env:
          name: TF_WORKSPACE
          command: echo $WORKSPACE
      - run: terragrunt apply -input=false


      